from django.contrib import admin
from . import models

admin.site.register(models.Country)
admin.site.register(models.State)
admin.site.register(models.City)
admin.site.register(models.Gender)
admin.site.register(models.MaritalType)
admin.site.register(models.ForgotPassword)
admin.site.register(models.Degree)
admin.site.register(models.UniversityBoard)
admin.site.register(models.Company)
admin.site.register(models.Skill)
admin.site.register(models.CandidateProfile)
admin.site.register(models.CandidateSocialNetwork)
admin.site.register(models.CandidateEducation)
admin.site.register(models.CandidateExperience)
admin.site.register(models.CandidateCertificationAttachment)
admin.site.register(models.CandidateAward)
admin.site.register(models.CandidateSkillUserMap)
admin.site.register(models.CandidatePortfolio)
admin.site.register(models.CandidateSummary)
admin.site.register(models.CandidateOtherField)
admin.site.register(models.CandidateLanguage)
admin.site.register(models.Languages)
admin.site.register(models.Fluency)
admin.site.register(models.NoticePeriod)
admin.site.register(models.IndustryType)
admin.site.register(models.CandidateProfileTheme)