# Generated by Django 2.2.8 on 2021-07-15 08:22

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateaward',
            name='award_img',
            field=models.FileField(max_length=500, null=True, upload_to=candidate.models.awards_document_path_handler),
        ),
        migrations.AlterField(
            model_name='candidatecertificationattachment',
            name='attached_certificate',
            field=models.FileField(max_length=500, null=True, upload_to=candidate.models.certificate_document_path_handler),
        ),
        migrations.AlterField(
            model_name='candidateexpdocuments',
            name='exp_document',
            field=models.FileField(max_length=500, null=True, upload_to=candidate.models.experience_document_path_handler),
        ),
        migrations.AlterField(
            model_name='candidateportfolio',
            name='project_document',
            field=models.FileField(max_length=500, null=True, upload_to=candidate.models.portfolio_document_path_handler),
        ),
    ]
