# Generated by Django 2.2.8 on 2021-07-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20210715_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateaward',
            name='summary',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecertificationattachment',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='job_description_responsibility',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidateportfolio',
            name='description',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='dob',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='website',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='zip_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
