# Generated by Django 2.2.8 on 2021-07-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20210719_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='url_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
