# Generated by Django 2.2.8 on 2021-07-20 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_auto_20210719_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for_job', models.BooleanField(default=False)),
                ('google_search', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_seo_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
