# Generated by Django 2.2.8 on 2021-07-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidateseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidatesocialnetwork',
            name='username',
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='grade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='end_salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='start_salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_password',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='url_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CandidateSEO',
        ),
    ]
