# Generated by Django 2.2.8 on 2021-07-20 12:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_candidateseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducation',
            name='summary',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
