# Generated by Django 2.2.8 on 2021-07-20 12:34

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_auto_20210720_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducation',
            name='certificate',
            field=models.FileField(max_length=1000, null=True, upload_to=candidate.models.degree_document_path_handler),
        ),
    ]
