# Generated by Django 2.2.8 on 2021-07-21 06:24

import candidate.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_auto_20210720_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateaward',
            name='award_img',
            field=models.FileField(max_length=1000, null=True, upload_to=candidate.models.awards_document_path_handler),
        ),
        migrations.AlterField(
            model_name='candidateaward',
            name='summary',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='candidateaward',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecertificationattachment',
            name='name_of_certificate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecertificationattachment',
            name='record_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecertificationattachment',
            name='summary',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='job_description_responsibility',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='candidateportfolio',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateportfolio',
            name='learning_from_project',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='candidateportfolio',
            name='link',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='about_me',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
