# Generated by Django 2.2.8 on 2021-08-02 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0012_candidateprofile_custom_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_counter_fields_id', to=settings.AUTH_USER_MODEL)),
                ('profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_counter_fields_id', to='candidate.Profile')),
            ],
        ),
    ]
