# Generated by Django 2.2.8 on 2021-08-07 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_candidatecounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_data_request',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='company_data_request',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='company_data_request',
            name='type_name',
        ),
        migrations.AlterField(
            model_name='company_data_request',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_candidate_hide_field_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company_data_request',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_hide_field_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company_data_request',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company_data_request',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile_hide_field_id', to='candidate.Profile'),
        ),
        migrations.DeleteModel(
            name='company_Hide_Fields_request',
        ),
    ]
