# Generated by Django 2.2.8 on 2021-10-25 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0036_auto_20211022_0920'),
        ('candidate', '0017_candidate_job_apply_detail_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JcrFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcr_apply', to=settings.AUTH_USER_MODEL)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccandidate_company_jcr_id', to=settings.AUTH_USER_MODEL)),
                ('jcr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcr_id', to='company.JCR')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_id', to='company.JobCreation')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_template_id', to='company.Template_creation')),
            ],
        ),
    ]
