# Generated by Django 2.2.8 on 2021-10-25 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0036_auto_20211022_0920'),
        ('candidate', '0018_jcrfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcrfill',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_company_jcr_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JcrRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primary', models.CharField(max_length=10)),
                ('Secondary', models.CharField(max_length=10)),
                ('Objective', models.CharField(max_length=10)),
                ('Total', models.CharField(max_length=10)),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcr_ratio', to=settings.AUTH_USER_MODEL)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcrratio_company_jcr_id', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcrratio_job_id', to='company.JobCreation')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_jcrratio_template_id', to='company.Template_creation')),
            ],
        ),
    ]
