# Generated by Django 2.2.8 on 2021-10-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_auto_20211025_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_job_apply_detail',
            name='notice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_applyjob_notice_period', to='candidate.NoticePeriod'),
        ),
    ]
