# Generated by Django 2.2.8 on 2021-07-15 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_candidate', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('ip', models.CharField(max_length=20)),
                ('device_type', models.CharField(max_length=50)),
                ('browser_type', models.CharField(max_length=50)),
                ('browser_version', models.CharField(max_length=50)),
                ('os_type', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0, null=True)),
                ('referral_number', models.CharField(max_length=20, null=True)),
                ('referred_by', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('ip', models.CharField(max_length=20)),
                ('device_type', models.CharField(max_length=50)),
                ('browser_type', models.CharField(max_length=50)),
                ('browser_version', models.CharField(max_length=50)),
                ('os_type', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=6)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
