# Generated by Django 2.2.8 on 2021-09-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
    ]
