# Generated by Django 2.2.8 on 2021-10-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarifyCandidateEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
            ],
        ),
    ]
