# Generated by Django 2.2.8 on 2021-07-15 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universal_Name', models.CharField(max_length=500)),
                ('compnay_type', models.CharField(choices=[('Public Company', 'Public Company'), ('Educational', 'Educational'), ('Self Employed', 'Self Employed'), ('Government Agency', 'Government Agency'), ('Non Profit', 'Non Profit'), ('Self Owned', 'Self Owned'), ('Privately Held', 'Privately Held'), ('Partnership', 'Partnership')], max_length=50)),
                ('company_logo', models.ImageField(upload_to='', verbose_name='company_logo_image')),
                ('speciality', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('contact_no1', models.CharField(max_length=10)),
                ('contact_no2', models.CharField(max_length=10)),
                ('founded_year', models.CharField(max_length=5)),
                ('employee_count', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001-5000', '1001-5000 employees'), ('5001-10,000', '5001-10,000 employees'), ('10,001+', '10,001+ employees')], max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_city', to='candidate.City')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_country', to='candidate.Country')),
                ('industry_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_industrytype', to='candidate.IndustryType')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_state', to='candidate.State')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSelectedPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_name', models.CharField(max_length=100)),
                ('is_selected', models.BooleanField(null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_check_candidate_id', to=settings.AUTH_USER_MODEL)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_check_company_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('request_status', models.IntegerField(default=0, null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_hire_id', to=settings.AUTH_USER_MODEL)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_id', to=settings.AUTH_USER_MODEL)),
                ('profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_id', to='candidate.Profile')),
            ],
        ),
    ]
