# Generated by Django 2.2.8 on 2021-09-17 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_company_data_request_zip_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_shortlistedcandidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('data', tinymce.models.HTMLField()),
                ('template_name', models.CharField(max_length=20)),
                ('html_data', tinymce.models.HTMLField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_requisites_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('contact_name', models.CharField(max_length=100, null=True)),
                ('target_date', models.DateField()),
                ('remote_job', models.BooleanField()),
                ('min_salary', models.CharField(max_length=10)),
                ('max_salary', models.CharField(max_length=10)),
                ('experience_year', models.CharField(max_length=10)),
                ('experience_month', models.CharField(max_length=10)),
                ('job_description', tinymce.models.HTMLField()),
                ('benefits', tinymce.models.HTMLField(max_length=100)),
                ('requirements', tinymce.models.HTMLField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('job_owner', models.CharField(max_length=100, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_city', to='candidate.City')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_create_company_id', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_country', to='candidate.Country')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_type_id', to='company.JobTypes')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_status_id', to='company.JobStatus')),
            ],
        ),
    ]
