# Generated by Django 2.2.8 on 2021-09-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_company_data_request_zip_link'),
        ('company', '0003_jobcreation_jobstatus_jobtypes_prerequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.CharField(max_length=20, null=True)),
                ('phone_no', models.CharField(max_length=20)),
                ('current_zip_code', models.CharField(max_length=10, null=True)),
                ('current_street', models.CharField(max_length=50, null=True)),
                ('permanent_zip_code', models.CharField(max_length=10, null=True)),
                ('permanent_street', models.CharField(max_length=50, null=True)),
                ('current_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_current_city', to='candidate.City')),
                ('current_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_current_country', to='candidate.Country')),
                ('current_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_current_state', to='candidate.State')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_gender', to='candidate.Gender')),
                ('permanent_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_permanent_city', to='candidate.City')),
                ('permanent_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_permanent_country', to='candidate.Country')),
                ('permanent_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_permanent_state', to='candidate.State')),
            ],
        ),
        migrations.CreateModel(
            name='InternalCandidateExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('start_date', models.CharField(max_length=100, null=True)),
                ('end_date', models.CharField(max_length=100, null=True)),
                ('summary', models.CharField(max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_company_id', to='candidate.Company')),
                ('internal_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_experience_id', to='company.InternalCandidate')),
                ('skills', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_skill_id', to='candidate.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='InternalCandidateEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, null=True)),
                ('start_date', models.CharField(max_length=50, null=True)),
                ('end_date', models.CharField(max_length=50, null=True)),
                ('is_pursuing', models.BooleanField(default=False, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('update_at', models.DateTimeField(max_length=200, null=True)),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_degree', to='candidate.Degree')),
                ('internal_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_id', to='company.InternalCandidate')),
                ('university_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_university', to='candidate.UniversityBoard')),
            ],
        ),
    ]
