# Generated by Django 2.2.8 on 2021-09-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_jobcreation_industry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyJobShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_id', to='company.JobCreation')),
                ('job_shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_shift_id', to='company.JobShift')),
            ],
        ),
    ]
