# Generated by Django 2.2.8 on 2021-09-24 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0006_companyjobshift_jobshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyjobshift',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_shift', to=settings.AUTH_USER_MODEL),
        ),
    ]
