# Generated by Django 2.2.8 on 2021-09-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_company_data_request_zip_link'),
        ('company', '0007_companyjobshift_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='internalcandidateexperience',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internalcandidateexperience',
            name='currently_working',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='InternalCandidateProfessionalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=20, null=True)),
                ('current_job_title', models.CharField(max_length=30, null=True)),
                ('highest_qualification', models.CharField(max_length=30, null=True)),
                ('expected_salary', models.CharField(max_length=20, null=True)),
                ('current_salary', models.CharField(max_length=20, null=True)),
                ('current_employer', models.CharField(max_length=30, null=True)),
                ('skills', models.CharField(max_length=100, null=True)),
                ('internal_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_professional_detail', to='company.InternalCandidate')),
                ('notice_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_notice_period', to='candidate.NoticePeriod')),
            ],
        ),
        migrations.CreateModel(
            name='InternalCandidatePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.CharField(choices=[('5day', '5 Days Working'), ('6day', '6 Days Working')], max_length=20)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_preference_city', to='candidate.City')),
                ('company_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_preference_company_type', to='company.CompanyType')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_preference_country', to='candidate.Country')),
                ('internal_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_preference', to='company.InternalCandidate')),
            ],
        ),
    ]
