# Generated by Django 2.2.8 on 2021-09-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_internalcandidateattachment_internalcandidateportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcandidateeducation',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
