# Generated by Django 2.2.8 on 2021-09-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_company_data_request_zip_link'),
        ('company', '0010_internalcandidateeducation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcandidateexperience',
            name='notice_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_exp_notice_period', to='candidate.NoticePeriod'),
        ),
    ]
