# Generated by Django 2.2.8 on 2021-09-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_internalcandidateexperience_notice_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcandidateportfolio',
            name='internal_candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_portfolio', to='company.InternalCandidate'),
        ),
    ]
