# Generated by Django 2.2.8 on 2021-10-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_internalcandidateportfolio_internal_candidate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcandidateexperience',
            name='notice_period',
        ),
    ]
