# Generated by Django 2.2.8 on 2021-10-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_company_data_request_zip_link'),
        ('company', '0014_internalcandidateaddedskill_internalcandidateskillusermap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternalCandidateSkillUserMap',
            new_name='InternalCandidateProfessionalSkill',
        ),
    ]
