# Generated by Django 2.2.8 on 2021-10-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_candidatesource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateSource',
            new_name='Source',
        ),
        migrations.CreateModel(
            name='InternalCandidateSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_source', models.CharField(max_length=200)),
                ('internal_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_source', to='company.InternalCandidate')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_source_id', to='company.Source')),
            ],
        ),
    ]
