# Generated by Django 2.2.8 on 2021-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20211006_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcandidatesource',
            name='custom_source',
        ),
        migrations.AddField(
            model_name='internalcandidatesource',
            name='custom_source_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
