# Generated by Django 2.2.8 on 2021-10-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20211006_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalCandidateNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('time', models.DateTimeField()),
                ('internal_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_candidate_notes_id', to='company.InternalCandidate')),
            ],
        ),
    ]
