# Generated by Django 2.2.8 on 2021-10-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_internalcandidatenotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreRequisites',
        ),
    ]
