# Generated by Django 2.2.8 on 2021-10-14 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0024_auto_20211014_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_job_creation',
            new_name='TemplateCategory',
        ),
    ]
