# Generated by Django 2.2.8 on 2021-10-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_workflowconfiguration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflows',
            old_name='status',
            new_name='active',
        ),
        migrations.AddField(
            model_name='workflows',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
    ]
