# Generated by Django 2.2.8 on 2021-10-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20211016_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_workflow_id', to='company.JobCreation')),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_workflow_id', to='company.Workflows')),
            ],
        ),
    ]
