# Generated by Django 2.2.8 on 2021-10-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_jobworkflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcreation',
            name='job_link',
            field=models.TextField(null=True),
        ),
    ]
