# Generated by Django 2.2.8 on 2021-10-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_jobcreation_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcreation',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
