# Generated by Django 2.2.8 on 2021-10-18 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0033_appliedcadidate_create_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppliedCadidate',
            new_name='AppliedCandidate',
        ),
    ]
