# Generated by Django 2.2.8 on 2021-10-19 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0034_auto_20211018_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcandidate',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_candidate_company_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobworkflow',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_job_workflow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowconfiguration',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_workflow_configuration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflows',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_workflow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowstages',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_workflow_stages', to=settings.AUTH_USER_MODEL),
        ),
    ]
