# Generated by Django 2.2.8 on 2021-10-22 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_auto_20211019_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcreation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcreation',
            name='created_by',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobcreation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appliedcandidate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_candidate_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appliedcandidate',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job_id', to='company.JobCreation'),
        ),
    ]
